Feature: add option for alternate shell icon
joshmedeski/tmux-nerd-font-window-name pull request #4
Opened 2023-03-23 18:46 UTC by zatchheems

## Alternate Shell Icon Feature

For some odd reason, the NerdFont icon `nf-dev-terminal` renders strangely when windows running shells are focused. It could be Kitty, it could be my theme; I've tried several different NerdFont options to no avail. Not sure what the problem is or if it's repeatable. I've added an option to change this icon from black-on-white to white-on-black, which renders correctly and looks quite a bit better on my machine, regardless of the weird focus problem.

I'm also thinking about adding a small preview for the icon difference in the README, but not sure if that's necessary. Please advise!

### Demo:

![icon-behavior](https://user-images.githubusercontent.com/8506829/227315173-c035e06b-e90f-40f7-8c35-d814de2e0dc7.gif)

### Detail:

<img width="346" alt="image" src="https://user-images.githubusercontent.com/8506829/227316084-8314e1d7-7680-44b5-97ee-a8248808875e.png">

2023-03-23 19:48 UTC, joshmedeski requested changes
Thanks for doing this! I'm thinking of offering a yml file or something so people can map whatever icons they want to whatever values, but this is helpful for now.

I've made a couple of suggestions to make it more flexible and cleanup the code.

2023-03-23 19:48 UTC, joshmedeski commented on README.md
> +set -g @tmux-nerd-font-window-name-alterate-shell-icon true
How about we accept a string to let people pick whatever icon they want?

```suggestion
set -g @tmux-nerd-font-window-name-shell-icon ""
```

2023-03-23 19:48 UTC, joshmedeski commented on bin/tmux-nerd-font-window-name
> +if [ "$ALTERNATE_SHELL_ICON" = true ]; then
I prefer we use a function to scope the data.

```
get_shell_icon() {
	local default_shell_icon=''
	local shell_icon="$(tmux show -gqv '@tmux-nerd-font-window-name-shell-icon')"
	[ -n "$shell_icon" ] && echo "$shell_icon" || echo "$default_shell_icon"
}

SHELL_ICON=$(get_shell_icon)
```

Please test this and clean it up as you see fit.

2023-03-23 19:55 UTC, zatchheems commented
thanks for the suggestions! I appreciate them especially because tmux config and plugins can get spaghetti-like without constant vigilance 🙂

I'll make those changes and test sometime today or tomorrow.

2023-03-23 20:22 UTC, zatchheems commented on bin/tmux-nerd-font-window-name
> +  fi
This differs from your suggestion, but I usually prefer verbosity over shorthand—it's a holdover from a few years in Rescript I think. I can use shorthand if preferred.

2023-03-24 15:52 UTC, joshmedeski approved these changes
Looks good to me 👍

2023-03-24 15:54 UTC, merged

2023-03-24 18:56 UTC, zatchheems commented
This is already merged, but just for future reference: applying **bold** styling to NerdFonts can cause them to behave unexpectedly. That's what caused the weird behavior in my screenshots.

_The more you know!_

2023-03-24 19:05 UTC, joshmedeski commented
Good to know, I might add some info to the README to let people know.